---
- name: Install MySQL client & server
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-client
    - mysql-server
    - python-mysqldb

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Setup MySQL creds for root user
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600

- name: Setup MySQL creds for vagrant user
  template:
    src: my.cnf.j2
    dest: /home/vagrant/.my.cnf
    owner: vagrant
    mode: 0600

- name: Setup MySQL root password
  mysql_user:
    name: root
    password:
    host: "{{ item }}"
    state: present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Setup empty database
  mysql_db:
    name: "{{ db_name }}"
    encoding: utf8
    collation: utf8_unicode_ci
    state: present
